plugins { id 'java' }

repositories { mavenCentral() }

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java { sourceCompatibility = JavaVersion.VERSION_25; targetCompatibility = JavaVersion.VERSION_25 }
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8'; options.release = 25 }

if (providers.gradleProperty('reference').isPresent()) {
    sourceSets.main.java.setSrcDirs(['../reference'])
}
if (providers.gradleProperty('grading').isPresent()) {
    sourceSets.test.java.srcDir('../tests')
}
test { useJUnitPlatform() }
