local M={}
function M.uses(doc)
  local result,seen=pandoc.List(),{}
  local function add(node)
    local target=node.target or node.src
    if not target:match('^[%a][%w+.-]*:') and not target:match('^//') and target:sub(1,1)~='#' then
      target=target:gsub('[?#].*$','')
      if target~='' and not seen[target] then result:insert(target);seen[target]=true end
    end
  end
  local function raw(node)
    if node.format=='html' then
      for target in node.text:gmatch('[sS][rR][cC]%s*=%s*["\']([^"\']+)["\']') do add({target=target}) end
      for target in node.text:gmatch('[hH][rR][eE][fF]%s*=%s*["\']([^"\']+)["\']') do add({target=target}) end
    end
  end
  doc:walk({Image=add,Link=add,RawBlock=raw,RawInline=raw});return result
end
function M.facts(raw,public,canonical)
  local root=quarto.project.directory
  local rawProjectRoots,seenProjects=pandoc.List(),{}
  -- Reuse pre-projection validation facts; retain paths only, never private bodies.
  for _,fact in ipairs(canonical or {}) do
    if fact.project then
      if fact.project:sub(1,1)~='/' or fact.project:sub(1,2)=='//' then error('RESOURCE.PROJECT_PATH_INVALID: '..fact.project) end
      local path=pandoc.path.normalize(pandoc.path.join({root,fact.project:sub(2)}))
      if not seenProjects[path] then rawProjectRoots:insert(path);seenProjects[path]=true end
    end
  end
  local input=quarto.doc.input_file;if pandoc.path.is_relative(input) then input=pandoc.path.join({root,input}) end
  local outputRoot=quarto.project.output_directory or root;if pandoc.path.is_relative(outputRoot) then outputRoot=pandoc.path.join({root,outputRoot}) end
  local rawUses,projectedUses=M.uses(raw),M.uses(public)
  local capturedFiles=pandoc.List()
  local publicUses={};for _,uri in ipairs(projectedUses) do publicUses[uri]=true end
  local view=raw.meta.course.view and pandoc.utils.stringify(raw.meta.course.view) or nil
  local generatedPrefix=input:gsub('%.[^./]+$','')..'_files/'
  -- Observe bytes while engine-generated files still live beside the input.
  -- The native writer may move them to outputRoot after this filter returns.
  for _,uri in ipairs(rawUses) do
    local decoded=uri:gsub('%%(%x%x)',function(h) return string.char(tonumber(h,16)) end)
    local source=decoded:sub(1,1)=='/' and pandoc.path.join({root,decoded:sub(2)}) or pandoc.path.join({pandoc.path.directory(input),decoded})
    source=pandoc.path.normalize(source)
    local file=io.open(source,'rb')
    if file then
      local bytes=file:read('*a');file:close()
      if bytes then
        local observed={source=source,output=pandoc.path.join({outputRoot,pandoc.path.make_relative(source,root)}),sha1=pandoc.utils.sha1(bytes)}
        -- PDF compilation consumes generated figures. Transport only referenced
        -- bytes, and never private generated bytes in a public sidecar.
        if FORMAT=='latex' and source:sub(1,#generatedPrefix)==generatedPrefix and (view=='full' or publicUses[uri]) then observed._bytes=bytes end
        capturedFiles:insert(observed)
      end
    end
  end
  return {source=pandoc.path.make_relative(input,root),format=FORMAT,view=raw.meta.course.view and pandoc.utils.stringify(raw.meta.course.view) or nil,
    rawProjectRoots=rawProjectRoots,effectiveBase=pandoc.path.directory(input),outputDirectory=outputRoot,outputFile=quarto.doc.output_file,rawUses=rawUses,projectedUses=projectedUses,capturedFiles=capturedFiles}
end
return M
