project:
  type: default
  render:
  - 01-intro.qmd
  - 02-language.qmd
  - 03-data.qmd
  - 04-development.qmd
  - 05-design.qmd
  - 06-concurrency.qmd
  - 07-applications.qmd
  - 08-quality.qmd
  output-dir: _output
  resources:
  - ./assets/**
  - '!materials/**'
  - '!**/*.qmd'
  pre-render:
  - _extensions/Afonenko-Course-Tools/course-core/entrypoints/pre.ts
  post-render:
  - _extensions/Afonenko-Course-Tools/course-core/entrypoints/post.ts
profile:
  default: student
  group:
  - - student
    - full
course:
  id: java-lectures
  validate: true
filters:
- course-core
- course-presentation
format:
  revealjs:
    theme: default
    show-notes: false
    slide-number: true
    revealjs-plugins:
    - course-navigation
lang: ru
