project:
  type: default
  render:
  - 01-intro.qmd
  - 02-language.qmd
  - 03-data.qmd
  - 04-development.qmd
  - 05-design.qmd
  - 06-concurrency.qmd
  - 07-applications.qmd
  - 08-quality.qmd
  output-dir: _output
  resources:
  - ./assets/**
  - '!materials/**'
  - '!**/*.qmd'
  - '!**/_*.qmd'
  - '!_generated/**'
  - '!_freeze/**'
  - '!.quarto/**'
  - '!_extensions/**'
  - '!**/*.rmd'
  - '!**/*.ipynb'
  - '!**/_output/**'
  - '!**/_site*/**'
  - '!**/_generated/**'
  - '!**/projects/**'
  - '!**/.superpowers/**'
  pre-render:
  - _extensions/Afonenko-Course-Tools/course-core/entrypoints/pre.ts
  post-render:
  - _extensions/Afonenko-Course-Tools/course-core/entrypoints/post.ts
  - _extensions/Afonenko-Course-Tools/reference-catalog/entrypoints/post.ts
  - ../_extensions/Afonenko-Course-Tools/course-site/entrypoints/collect.ts
profile:
  default: student
  group:
  - - student
    - full
filters:
- course-core
- course-presentation
- reference-catalog
format:
  revealjs:
    shift-heading-level-by: -1
    slide-level: 2
    navigation-mode: linear
    theme: default
    slide-number: true
    revealjs-plugins:
    - course-navigation
lang: ru
reference-catalog:
  namespace: lectures
fail-if-warnings: true
