plugins { id 'java' }
repositories { mavenCentral() }
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.4'
}
java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}
tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}
if (project.hasProperty('reference')) {
    sourceSets.main.java.setSrcDirs(['../reference'])
}
if (project.hasProperty('grading')) {
    sourceSets.test.java.srcDir('../tests/junit')
}
test { useJUnitPlatform() }
